### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by gabrielantao** [gabrielantao/Projeto-PJT#1]
== Fase 1 ==
- [ ] Testes de funcionalidade de aquisição de sinal de um canal e alterar parâmetros para teste
- [ ] Gerar armazenamento CSV, e analizar consistência dos dados exportados
- [ ] Testar funcionalidade de aquisição de multicanais
- [ ] Melhorar parser para gerar .py com todas as constantes e outro com todas as funções tudo automaticamente documentado a partir do próprio parse do arquivo de cabeçalho .h
- [ ] Gerar herança de classes para os tipos definidos no .h (Int16, Int32 ...)
- [ ] Reutilizar funcionalidades do módulo do daqmx anexado ao repositório
- [ ] Planejamento da abstração dos principais objetos componentes do DAQmx
- [ ] Transformar os closures em decorators
- [ ] Dar suporte ao DAQmx Base (geração dos módulos e funcionamento pleno)
